### ISSUE TITLE
HTTPS -> HTTP

### ISSUE THREAD

**Issue by glacialcascade** [dragonitefll/pet-ball-web#1]
Ok so googleapis uses http. I can't access it with https, and when i put it as https in the code, I still recieve an error that's something like "Mixed Content: "https://tyrfaugeyubgfjhbwsdhjhjcvf" was loaded over HTTPS. but "http://ajax.googleapis.com/agrebdvgfdcvreuibgjraeinkangka" is insecure.""
So how to fix? Don't use googleapis.

**Comment by glacialcascade** [comment]
nvm looking at wrong branch

**Comment by websiteguy1222** [comment]
Ok
